### ISSUE TITLE
Checklist - Preparation for release

### ISSUE THREAD

**Issue by chesterbr** [chesterbr/flickr_backup#2]
- [x] Triple check it's ok to share the secret
- [x] Consider solving #1 (nah)
- [x] Publicize the Flickr app (requires screenshot)
- [x] Publicize the repo
- [ ] Blog post

**Comment by chesterbr** [comment]
not blog-post-worthy
